# SPDX-FileCopyrightText: 2023 Sergio Durigan Junior
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Perform Roundcube installation tasks
  block:
    - name: Validate Roundcube configuration
      when: roundcube_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install Roundcube
      when: roundcube_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"
  tags:
    - setup-all
    - setup-roundcube
    - install-all
    - install-roundcube

- name: Perform Roundcube uninstallation tasks
  block:
    - name: Uninstall Roundcube
      when: not roundcube_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
  tags:
    - setup-all
    - setup-roundcube
