# SPDX-FileCopyrightText: 2023 Sergio Durigan Junior
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform Roundcube installation tasks
  when: roundcube_enabled | bool
  tags:
    - setup-all
    - setup-roundcube
    - install-all
    - install-roundcube
  block:
    - name: Validate Roundcube configuration
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
    - name: Install Roundcube
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform Roundcube uninstallation tasks
  when: not roundcube_enabled | bool
  tags:
    - setup-all
    - setup-roundcube
  block:
    - name: Uninstall Roundcube
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
